### ISSUE TITLE
Add SSL Certificate to domain

### ISSUE THREAD

**Issue by jamesnorbertowork** [CodeforHawaii/newwebsite#1]
<img width="1013" alt="Screen Shot 2021-03-10 at 3 51 11 PM" src="https://user-images.githubusercontent.com/67208442/110588570-89c09f80-81b8-11eb-9539-3cf5affe6444.png">

**Comment by avenmia** [comment]
By manually changing the protocol to https in the address bar, I can verify the site appears to have a valid certificate. 

![Certificate information](https://user-images.githubusercontent.com/17712276/145931988-1c740b67-ae2b-4aab-9074-503bb6372faa.png)


It would be nice if there was an https redirect for the website. 

The site appears to be a static site hosted in an s3 bucket. [Here is the documentation on how to create redirects](https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html)

**Comment by Torivino** [comment]
Tori to follow up with Marion to see who would have these permissions

**Comment by avenmia** [comment]
This is actually for the old website and is fixed with the new website.
