### ISSUE TITLE
Verbiage for Holo Holo

### ISSUE THREAD

**Issue by Torivino** [CodeforHawaii/newwebsite#24]
**What is this project about?**
In partnership with [American Civil Liberties Union of Hawai`i](https://acluhi.org/) (ACLUHI), the purpose of Holo Holo is to use your geo-location to assist understanding of whose land you are on and your civil rights there. This app determines if a location is Public, Private, or Restricted and will provide you with information about your rights, based on activity.

**What are the project goals?**
Our goal is to create an MVP for the Island of Oahu and later expand the app to be state-wide. In addition, the ability for the user to download a zoomable map in advance.

**What are the project roles involved?**

**Comment by avenmia** [comment]
According to @bobbykimani  This is an inactive project. Do we still want this on the website?

**Comment by Torivino** [comment]
**What is this project about?**
In partnership with [American Civil Liberties Union of Hawai`i](https://acluhi.org/) (ACLUHI), the purpose of Holo Holo is to use your geo-location to assist understanding of whose land you are on and your civil rights there. This app determines if a location is Public, Private, or Restricted and will provide you with information about your rights, based on activity.

**What are the project goals?**
Our goal is to create an MVP for the Island of Oahu and later expand the app to be state-wide. In addition, the ability for the user to download a zoomable map in advance.

**What are the project roles involved?**
