### ISSUE TITLE
Add Onboarding content

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/newwebsite#26]
This is any content that a new member of Code For Hawaii may want to know. Some examples are:

* Mission Statement
  * To foster efficient and fair government through **civic engagement** by collaborating with government officials and leveraging **technologies that promote openness and accountability.**
* Our Team Culture?
  * Project Leaders
  * MC/Onboarding lead
  * Technical onboarder
  * Storyteller
  * Active brigade member

Additional Considerations:
* How will this section look?
* What order of the page will this be placed?

**Comment by bentut** [comment]
Meet & Greet
We start each meeting with a land acknowledgement, Code for Americaʻs Code of Conduct, and a full round of introductions including your name, where you are calling from and a question of the day.

Debrief on projects and announcements
We will share key milestones, updates, and blockers on projects as well as relevant news from Code for America including participating in national events such as Brigade Congress, National Day of Civic Hacking, and Code for America Summit. We also occasionally welcome guests and partners to share what they are working on so we can continue to learn about how to have impact in Hawaii.

Participate in breakout rooms
Each month the brigade selects a "Focus Project" that we all work on together as a brigade. We also work on developing several other projects in the "background" through our "Discovery Track". Each meetup we create breakout rooms as needed to drive toward our milestones on the "Focus Project" or explore projects in our "Discovery Track"

**Comment by avenmia** [comment]
@bentut it looks like the website has the Meet & Greet, Debrief, and Participate sections, but the text is different. Is the text on the website the most recent version?

**Comment by avenmia** [comment]
#39
