### ISSUE TITLE
Update Food Oasis Project Description

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/newwebsite#27]
Fill in:
* What is this project about?
* What are the project goals?
* What are the project roles involved?

**Comment by orobor0s** [comment]
I'm working on this one

**Comment by stdyrm** [comment]
Hi, here's verbiage for the Food Oasis project. Feel free to modify anything

**What is this project about?**
Food Oasis is an interactive web app for people to locate nearby public food resources. Code for Hawaiʻi built on the tool created by fellow Code For America member Hack for LA Brigade, mapping Oʻahu resources provided by local food rescue nonprofit Aloha Harvest.

**What are the project goals?**
The goal of Food Oasis is to provide up-to-date and accurate information on local public food resources. By collaborating with local nonprofits and contributing to a common codebase with other brigades, we hope to create a maintainable, one-stop resource that can extend beyond the limitations of any single organization.

**What are the project roles involved?**
UX design, frontend development (Javascript, React), backend development (NodeJS, Express, PostgreSQL), storytelling (how do we make this meaningful for food-seekers, nonprofits, and the local community)
