### ISSUE TITLE
Update Second Chances Project Description

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/newwebsite#28]
Fill in:
* What is this project about?
* What are the project goals?
* What are the project roles involved?

**Comment by kmal808** [comment]
Move Second Chances and Holo Holo  to "completed projects" section per Suchandra. Will still need project description.

**Comment by bentut** [comment]
![Second Chances](https://user-images.githubusercontent.com/152147/159412094-1f4fea51-e46c-4dc9-9dab-65407bbe5153.png)

**Comment by bentut** [comment]
![Screen+Shot+2019-08-30+at+2 06 53+PM](https://user-images.githubusercontent.com/152147/159416014-16596f87-6315-47bf-9320-5a385f01df00.png)
