### ISSUE TITLE
Fix Timeline

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/newwebsite#29]
This involves either talking with Ryan about some of the missing sections of the timeline or removing the timeline

The spots that need fixing are:
* December 2012 Transition to Full Service
* July 2014 Phase Two Expansion

Also there should be some discussion on the existing sections and whether those are still up to date.

**Comment by avenmia** [comment]
I'm going to remove the timeline for now and we can add it back in when there's more information to add.

**Comment by avenmia** [comment]
#32

**Comment by bentut** [comment]
Content for Timeline:
2012: Honolulu Organizes [CityCamp 2012](https://www.facebook.com/CityCampHNL/). That was the first local event to introduce Code for America, a national organization that aims to “build open source technology and organize a network of people dedicated to making government services simple, effective, and easy to use.”

2012: Code for Hawaii joins the inaugural cohort of [Brigades ](https://web.archive.org/web/20160411213920/http://www.codeforamerica.org/blog/2012/08/23/introducing-the-brigade-captains-program/)along with Portland, ME; Austin; Boston; Lexington; Philly; Chicago; Denver; San Diego; Grand Rapids; Detroit; Arlington; Asheville; Oakland; Bend; Alexandria

2015: Code for Hawaii welcomes a [reboot](http://www.hawaiiweblog.com/2015/04/28/code-for-hawaii-ready-for-reboot) and new leadership.

2020: Code for Hawaii develops [Kaiulu Strategic Promise]
(https://github.com/CodeforHawaii/newwebsite/files/8321556/CFH_StrategicPromise_FINAL.pdf) and clarifies strategic vision for the organization going forward!

**Comment by avenmia** [comment]
#37 

@bentut  I added the timeline back in based on your suggestions above. I left some notes in the PR, but if it's easier to address them here that's fine too!
