### ISSUE TITLE
Fix the contact form at the bottom

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/newwebsite#30]
This includes
* Verifying if the form works
  * If the form doesn't work are we keeping it
*  Consulting with Ben or Jess on who wants to monitor the email

**Comment by avenmia** [comment]
The form validation works, however we need a way to deploy the php code since GitHub pages is for static content only.
https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

We'll move this for after March, and look at the best way to deploy the php code or some other solution. @kmal808

**Comment by avenmia** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP_eb.html

**Comment by avenmia** [comment]
Going to delete the contact form for now and possibly add it back in after March

**Comment by StoneCodeKilla** [comment]
Im going to work on this
