### ISSUE TITLE
Update the social media links

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/newwebsite#31]
This includes:
* Determining which links are still relevant
* Determining what new links should be added
  * Meetup link
  * Github link

**Comment by kmal808** [comment]
None of the social links are active, all three can be removed, and GitHub and MeetUp links/icons added.

**Comment by avenmia** [comment]
I believe @boobeh123 had changes for this in progress.

**Comment by orobor0s** [comment]
@boobeh123 updated this
